version: '3.8'

services:
  react-app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npx cross-env NODE_ENV=development npm start"
